version: 2.1
executors:
  node-executor:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
commands:
  save_files:
    steps:
      - persist_to_workspace:
          root: ~/repo
          paths: .
  read_files:
    steps:
      - attach_workspace:
          at: ~/repo
jobs:
  install_dependency:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - save_files
  build:
    executor: node-executor
    steps:
      - read_files
      - run:
          name: build
          command: npm run build
      - save_files
  npm_test:
    executor: node-executor
    steps:
      - read_files
      - run:
          name: Run tests
          command: npm test
  deploy:
    executor: node-executor
    steps:
      - read_files
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  npm_deploy:
    jobs:
      - install_dependency:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - install_dependency
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - npm_test:
          requires:
            - install_dependency
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build
            - npm_test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
