version: 2.1
executors:
  node-executor:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
jobs:
  install_dependency:
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    executor: node-executor
    steps:
      - run:
        name: build
        command: npm run build
      - persist_to_workspace:
        root: ~/repo
        paths: .
  npm_test:
    executor: node-executor
    steps:
      - run:
        name: Run tests
        command: npm test
  deploy:
    executor: node-executor
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - install_dependency
      - build:
          requires:
            - install_dependency
      - npm_test:
          requires:
            - install_dependency
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - build
            - npm_test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
